---
title: "Pregunta 1"
author: "Manuel & Thommas"
date: "2024-12-17"
output: word_document
---

Pregunta 1:

De las siguientes preguntas, clasifica cada una como descriptiva, exploratoria,
inferencia, predictiva o causal, y razona brevemente (una frase) el porqué:

1. Dado un registro de vehículos que circulan por una autopista, disponemos de su
marca y modelo, país de matriculación, y tipo de vehículo (por número de
ruedas). Con tal de ajustar precios de los peajes, ¿Cuántos vehículos tenemos
por tipo? ¿Cuál es el tipo más frecuente? ¿De qué países tenemos más vehículos?

Clasificación: Descriptiva
Razón: El registro de vehículos está basado en un conjunto de datos estadísticos como tipo, marca, modelo… Estos conjuntos de datos solo busca identificar y categorizar los datos, no busca ni relaciones ni predicciones 


2. Dado un registro de visualizaciones de un servicio de video-on-demand, donde
disponemos de los datos del usuario, de la película seleccionada, fecha de
visualización y categoría de la película, queremos saber ¿Hay alguna preferencia
en cuanto a género literario según los usuarios y su rango de edad?

Clasificación: Exploratoria
Razón: Este registro de visualizaciones buscar obtener una relación entre películas (entre los datos) ya vista y posibles películas similares.



3. Dado un registro de peticiones a un sitio web, vemos que las peticiones que
provienen de una red de telefonía concreta acostumbran a ser incorrectas y
provocarnos errores de servicio. ¿Podemos determinar si en el futuro, los
próximos mensajes de esa red seguirán dando problemas? ¿Hemos notado el
mismo efecto en otras redes de telefonía?

Clasificación: Predictiva
Razón: El registro de peticiones a un sitio web,  el modelo busca evitar que el problema siga siendo recurrente para el futuro. Por lo que se pueden hacer un modelo de patrones para evitar o detectar posibles problemas en el futuro


4. Dado los registros de usuarios de un servicio de compras por internet, los
usuarios pueden agruparse por preferencias de productos comprados.
Queremos saber si ¿Es posible que, dado un usuario al azar y según su historial,
pueda ser directamente asignado a un o diversos grupos?

Clasificación: Inferencial
Razón: Este registro busca recopilar toda la información de preferencias (patrones) de compra de los usuarios para luego a partir de estos patrones generar una sugerencia de productos que estén relacionados. Algo muy común en las plataformas de shopping 

Pregunta 2

Abordaremos este problema recopilando, manipulando y analizando datos de las conexiones de protocolo TCP para poder reducir la lista de posibles culpables. Primero obtendremos los datos mediante los LOGS de conexión registrados en cada máquina de los empleados, como segunda parte procesaremos los datos importando los registros en R, procederemos a la limpieza de datos duplicados o inconsistentes , formateamos timestamps para asegurarnos de que estarán en el mismo formato. Luego como tercer paso haríamos análisis visualizando la distribución de las conexiones para identificar patrones , tambien podriamos hacer una comparaciones de las conexiones registradas con la lista de puertos y/o servicios autorizados, finalmente visualizamos los datos mediante gráficos como histogramas , diagramas de red y Heat Maps para visualizar frecuencias de conexiones , mapear relaciones entre IPS e identificar aumentos de actividad sospechosa.
:

