---
title: "Pregunta 1"
author: "Manuel & Thommas"
date: "2024-12-17"
output: word_document
---

Pregunta 1:

De las siguientes preguntas, clasifica cada una como descriptiva, exploratoria,
inferencia, predictiva o causal, y razona brevemente (una frase) el porqué:

1. Dado un registro de vehículos que circulan por una autopista, disponemos de su
marca y modelo, país de matriculación, y tipo de vehículo (por número de
ruedas). Con tal de ajustar precios de los peajes, ¿Cuántos vehículos tenemos
por tipo? ¿Cuál es el tipo más frecuente? ¿De qué países tenemos más vehículos?

Clasificación: Descriptiva
Razón: El registro de vehículos está basado en un conjunto de datos estadísticos como tipo, marca, modelo… Estos conjuntos de datos solo busca identificar y categorizar los datos, no busca ni relaciones ni predicciones 


2. Dado un registro de visualizaciones de un servicio de video-on-demand, donde
disponemos de los datos del usuario, de la película seleccionada, fecha de
visualización y categoría de la película, queremos saber ¿Hay alguna preferencia
en cuanto a género literario según los usuarios y su rango de edad?

Clasificación: Exploratoria
Razón: Este registro de visualizaciones buscar obtener una relación entre películas (entre los datos) ya vista y posibles películas similares.
